### ISSUE TITLE
Error when running ConTxT.sh

### ISSUE THREAD

**Issue by mradz19** [normanpavelka/MeTRS#1]
I am attempting to use MeTRS to profile bacteria within human samples following total RNA sequencing. I have followed all of the steps to generate the bowtie index and parse the Silva taxonomy files (using the provided database just to test the program). However when I attempt to run the ConTxT.sh script I get the following error:

Traceback (most recent call last):
  File "process.py", line 53, in <module>
    results.append(process(reads))
  File "process.py", line 21, in process
    minLevel = min(map(lambda x: len(x), levels))
ValueError: min() arg is an empty sequence

I can't quite work out what is going here.

**Comment by shepp-hub** [comment]
I got the same error and fixed it by decompressing the gzipped fastq files.
This allowed the analysis to crash much later, with a different error:
Traceback (most recent call last):
  File "process.py", line 48, in <module>
    results.append(process(reads))
  File "process.py", line 19, in process
    levels = map(lambda x: taxa[x[1]], reads)
  File "process.py", line 19, in <lambda>
    levels = map(lambda x: taxa[x[1]], reads)
KeyError: '+'

**Comment by DrNyao** [comment]
KeyError: '+' can be fixed by add
 | sed -e "s/\ /\_/g"
just after awk command in ConTxT.sh

Also, if you get some trouble that bowtie return very small amount hit, you can convert Silva library fasta file into DNA sequence (convert "U" to "T").

But still analysis crush in the process of python script with following error:

 Traceback (most recent call last):
  File "process.py", line 48, in <module>
    results.append(process(reads))
  File "process.py", line 30, in process
    maxPercentage = float(max(map(lambda x: counts[x], counts.keys()))) / len(reads)
ValueError: max() arg is an empty sequence

I really want to fix it !

**Comment by DrNyao** [comment]
I fixed it.
I changed python version from 3.8.3 to 2.7 by conda environment then error with "ValueError: max() arg is an empty sequence" was disappeared.

**Comment by DrNyao** [comment]
Also, awk command should be changed as following

awk 'BEGIN{FS="\t"}{print $1 "\t" $3}'

So, I think that entire shell script should be changed like

#!/bin/sh
INPUT=/path/to/input/directory  #Requires only fastq files in the directoryOUTPUT=/path/to/output/directorySilva_reannotated=/path/to/Silva_reannotated.txt Silva_bowtie_index=/path/to/Silva/bowtie_prefix

for entry in `ls $INPUT`
do
echo  "$entry"
(bowtie --threads 14 -a -v 3 --best --strata --chunkmbs 1000 -x ${Silva_bowtie_index} ${INPUT}/${entry} | awk 'BEGIN{FS="\t"}{print $1 "\t" $3}' | sed -e "s/\ /\_/g" > ${OUTPUT}/${entry}.twocol) 2> ${OUTPUT}/${entry}.log
python process.py ${OUTPUT}/${entry}.twocol $Silva_reannotated ${OUTPUT}/${entry}_abundances.txt
done

And, fasta file from Silva database should be converted to DNA sequence (convert "U" to "T") before running bowtie_build.
